apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-postgres
  labels:
    db: polar-postgres
spec:
  selector:
    matchLabels:
      db: polar-postgres
  template:
    metadata:
      labels:
        db: polar-postgres
    spec:
      containers:
        - name: polar-postgres
          image: postgres:15.0
          env:
            - name: POSTGRES_USER
              value: polarAdmin
            - name: POSTGRES_PASSWORD
              value: polar@postgres123!@#
            - name: POSTGRES_DB
              value: polar_db
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init-sql

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  shema-postgres.sql: |
    CREATE SCHEMA IF NOT EXISTS catalogsvc;
    CREATE SCHEMA IF NOT EXISTS ordersvc;

---
apiVersion: v1
kind: Service
metadata:
  name: polar-postgres
  labels:
    db: polar-postgres
spec:
  type: ClusterIP
  selector:
    db: polar-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432